blank_issues_enabled: true
contact_links:
  - name: ğŸ¤” Questions and Help
    url: https://github.com/cgiesche/streamdeck-homeassistant/discussions
    about: This issue tracker is not for support questions. Please refer to our Discussions.
  - name: ğŸš€ Feature Request
    url: https://github.com/cgiesche/streamdeck-homeassistant/discussions/new?category=feature-requests
    about: Remember to search for existing feature requests and "up-vote" any you like
  - name: ğŸ› Report a bug
    url: https://github.com/cgiesche/streamdeck-homeassistant/issues/new
    about: I you thing you found a bug that affects everyone, you can create an issue here.
